backup:
  environment:
    CRON_SCHEDULE: ${CRON_SCHEDULE}
    BACKEND: ${BACKEND}
    TARGET_PATH: ${TARGET_PATH}
    BK_FULL_FREQ: ${BK_FULL_FREQ}
    BK_KEEP_FULL: ${BK_KEEP_FULL}
    BK_KEEP_FULL_CHAIN: ${BK_KEEP_FULL_CHAIN}
    VOLUME_SIZE: ${VOLUME_SIZE}
    DEBUG: false
    DISABLE_DUMP : ${DISABLE_DUMP}
    DISABLE_DUMP_RANCHER: ${DISABLE_DUMP_RANCHER}
    FTP_PASSWORD: ${FTP_PASSWORD}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
    AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
    CLOUDFILES_USERNAME: ${CLOUDFILES_USERNAME}
    CLOUDFILES_APIKEY: ${CLOUDFILES_APIKEY}
    DPBX_ACCESS_TOKEN: ${DPBX_ACCESS_TOKEN}
    GS_ACCESS_KEY_ID: ${GS_ACCESS_KEY_ID}
    GS_SECRET_ACCESS_KEY: ${GS_SECRET_ACCESS_KEY}
    GOOGLE_DRIVE_ACCOUNT_KEY: ${GOOGLE_DRIVE_ACCOUNT_KEY}
    SWIFT_USERNAME: ${SWIFT_USERNAME}
    SWIFT_PASSWORD: ${SWIFT_PASSWORD}
    SWIFT_AUTHURL: ${SWIFT_AUTHURL}
  labels:
    io.rancher.sidekicks: backup-data
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
  tty: true
  image: webcenter/rancher-backup:1.0.2
  stdin_open: false
  privileged: true
  volumes_from:
    - backup-data

backup-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
    - /backup
  net: none
  command: /bin/true
